module.exports = {
    '01':'Make Public Statement',
    '02':'Appeal',
    '03':'Express Intent to Cooperate',
    '04':'Consult',
    '05':'Engage in Diplomatic Cooperation',
    '06':'Engage in Material Cooperation',
    '07':'Provide Aid',
    '08':'Yield',
    '09':'Investigate',
    '10':'Demand',
    '11':'Disapprove',
    '12':'Reject',
    '13':'Threaten',
    '14':'Protest',
    '15':'Exhibit Force Posture',
    '16':'Reduce Relations',
    '17':'Coerce',
    '18':'Assualt',
    '19':'Fight',
    '20':'Use Unconventional Mass Violence'
};
